apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: config-watcher-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]