apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc-1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: hostpath