apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hostpath
provisioner: kubevirt.io.hostpath-provisioner
reclaimPolicy: Delete
parameters:
  storagePool: local
volumeBindingMode: Immediate