apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
  - ../../base

patches:
  - target:
      kind: SecretGenerator
      name: my-secret-generator
    path: cr-patch.yaml
  - target:
      kind: CronJob
      name: secret-generator
    path: cronjob-patch.yaml