apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: velero-backups
  config:
    region: minio
    s3Url: http://minio.velero.svc:9000
    s3ForcePathStyle: "true"
  credential:
    name: cloud-credentials
    key: cloud
