
apiVersion: v1
kind: ConfigMap
metadata:
  name: restic-config
  namespace: velero
data:
  restic: "true"
  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: velero
  namespace: velero
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: velero
  template:
    metadata:
      labels:
        app.kubernetes.io/name: velero
    spec:
      serviceAccountName: velero-sa
      containers:
      - name: velero
        image: velero/velero:v1.15.2
        command:
          - /velero
        args:
          - server
        env:
          - name: VELERO_FEATURES
            valueFrom:
              configMapKeyRef:
                name: restic-config
                key: enable
        volumeMounts:
        - name: plugins
          mountPath: /plugins
      volumes:
      - name: plugins
        emptyDir: {}

---

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: velero-node-agent
  namespace: velero
spec:
  selector:
    matchLabels:
      component: node-agent
  template:
    metadata:
      labels:
        component: node-agent
    spec:
      serviceAccountName: velero-sa
      containers:
      - name: velero
        image: velero/velero:v1.15.2
        command:
          - /velero
        args:
          - node-agent
        env:
          - name: VELERO_NAMESPACE
            value: "velero"
          - name: VELERO_FEATURES
            value: "EnableNodeAgent,EnableCSI"
        securityContext:
          runAsUser: 1000
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - mountPath: /var/lib/kubelet/pods
          name: host-pods
          mountPropagation: HostToContainer
      volumes:
      - name: host-pods
        hostPath:
          path: /var/lib/kubelet/pods
          type: DirectoryOrCreate

