apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db
type: Opaque
data:
  MYSQL_USER: ZGV2dXNlcg==
  MYSQL_PASSWORD: ZGV2cGFzcw==
  MYSQL_DATABASE: ZGV2bXlzcWw=
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=