apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db
type: Opaque
data:
  MYSQL_USER: ZGV2dXNlcg==
  MYSQL_PASSWORD: c2VjdXJlcHJvZHBhc3N3b3Jk
  MYSQL_DATABASE: ZGV2bXlzcWw=
  MYSQL_ROOT_PASSWORD: Vnl9Klg1LnUiXHM0KU5Kb1d6elo6T01a