apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: monitoring
data:
  metrics.conf: |
    server {
      listen 8080;
      location /metrics {
        stub_status on;
      }
    }