apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-metrics
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-metrics
  template:
    metadata:
      labels:
        app: nginx-metrics
    spec:
      containers:
      - name: nginx
        image: bitnami/nginx
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: config-volume
          mountPath: /opt/bitnami/nginx/conf/server_blocks
      volumes:
      - name: config-volume
        configMap:
          name: nginx-config