apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: secretgenerators.custom.example.com
spec:
  group: custom.example.com
  names:
    kind: SecretGenerator
    listKind: SecretGeneratorList
    plural: secretgenerators
    singular: secretgenerator
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                secretName:
                  type: string