apiVersion: batch/v1
kind: CronJob
metadata:
  name: secret-generator
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 300
      template:
        spec:
          serviceAccountName: secret-operator-sa
          containers:
            - name: secret-generator
              image: default-route-openshift-image-registry.apps-crc.testing/default/secret-operator:latest
              imagePullPolicy: Always
          restartPolicy: OnFailure
  successfulJobsHistoryLimit: 1 
  failedJobsHistoryLimit: 1