apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
    - name: htpasswd_provider
      type: HTPasswd
      htpasswd:
        fileData:
          name: htpasswd-secret

---

apiVersion: v1
kind: Secret
metadata:
  name: htpasswd-secret
  namespace: openshift-config
  annotations:
    kubernetes.io/service-account.name: htpasswd-secret
stringData:
  htpasswd: |
    tester:$apr1$examplehash$examplepasswordhash

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tester-edit-dev
  namespace: dev
subjects:
  - kind: User
    name: tester
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: edit
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tester-edit-test
  namespace: test
subjects:
  - kind: User
    name: tester
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: edit
  apiGroup: rbac.authorization.k8s.io

---