apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - target:
      kind: SecretGenerator
      name: my-secret-generator
    path: cr-patch.yaml
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: prod
  - target:
      kind: CronJob
      name: secret-generator
    path: cronjob-patch.yaml