apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod

resources:
  - ../../base

patches:
  - path: cr-patch.yaml
  - target:
      kind: Namespace
    patch: |-
      - op: replace
        path: /metadata/name
        value: prod