apiVersion: v1
kind: Pod
metadata:
  name: allowed-nginx
  namespace: default
spec:
  serviceAccountName: secure-sa
  containers:
    - name: nginx
      image: bitnami/nginx
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsNonRoot: true
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true