apiVersion: v1
kind: Pod
metadata:
  name: allowed-nginx
  namespace: default
spec:
  serviceAccountName: secure-sa
  securityContext:
    runAsUser: 1000
  containers:
    - name: nginx
      image: bitnami/nginx
      securityContext:
        allowPrivilegeEscalation: false
      volumeMounts:
        - name: config-volume
          mountPath: /etc/nginx
  volumes:
    - name: config-volume
      emptyDir: {}