apiVersion: v1
kind: Pod
metadata:
  name: allowed-nginx
  namespace: default
  annotations:
    openshift.io/scc: restricted-scc
spec:
  serviceAccountName: secure-sa
  containers:
    - name: nginx
      image: bitnami/nginx
      imagePullPolicy: IfNotPresent
      securityContext:
        runAsUser: 1000
        readOnlyRootFilesystem: true