apiVersion: v1
kind: Pod
metadata:
  name: blocked-nginx
  namespace: default
  annotations:
    openshift.io/scc: restricted-scc
spec:
  serviceAccountName: secure-sa
  securityContext:
    runAsUser: 0
  containers:
    - name: nginx
      image: bitnami/nginx
      imagePullPolicy: IfNotPresent
      securityContext:
        allowPrivilegeEscalation: true
      volumeMounts:
        - name: host-volume
          mountPath: /host
  volumes:
    - name: host-volume
      hostPath:
        path: /etc/nginx