apiVersion: v1
kind: Pod
metadata:
  name: blocked-nginx
  namespace: default
spec:
  serviceAccountName: secure-sa
  containers:
    - name: nginx
      image: bitnami/nginx
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
        runAsUser: 0