apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secure-sa-scc-binding
  namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:restricted
subjects:
  - kind: ServiceAccount
    name: secure-sa
    namespace: default