resources:
- ../../base

nameSuffix: -dev

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: ns-secret.yaml
  target:
    kind: Secret
    name: cs-mysql-secret
    namespace: dev
- path: secret.yaml
- path: networkpolicy.yaml