resources:
- ../../base

nameSuffix: -dev

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
- path: ns-secret.yaml
  target:
    kind: Secret
    name: cs-mysql-secret
- path: secret.yaml
- path: networkpolicy.yaml
- patch: |-
    - op: add
      path: /metadata/namespace
      value: dev
  target:
    kind: Secret
    name: cs-mysql-secret
    version: v1
