resources:
- ../../base

nameSuffix: -dev

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesStrategicMerge:
- ns-secret.yaml

patches:
- path: secret.yaml
- path: networkpolicy.yaml