apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
spec:
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: default-route-openshift-image-registry.apps-crc.testing/dev/capstone-app:latest
          env:
            - name: CAPSTONE
              value: "DEV"
            - name: DB_HOST
              value: mysql-dev.db.svc.cluster.local
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: cs-mysql-secret-dev
                  key: MYSQL_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: cs-mysql-secret-dev
                  key: MYSQL_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: cs-mysql-secret-dev
                  key: MYSQL_DATABASE
