name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say Hello!
        run: echo "Hello, World!"

      - name: list files
        run: ls -a
